name: production
on:
    push:
        branches: ["production"]
permissions:
  id-token: write
  contents: read
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Build application
              run: |
                dotnet restore
                dotnet publish
            - name: Create zip file
              run: |
                zip -r minapi.zip MinimalAPI/bin/Release/net8.0/publish
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: minapi.zip
                path: ./minapi.zip
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download zip
              uses: actions/download-artifact@v4
              with:
                name: minapi.zip
            - name: Authenticate with Azure
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            - name: Deploy code to azure app
              uses: azure/cli@v2
              with:
                azcliversion: latest
                inlineScript: |
                  az webapp deploy --resource-group debeir-rg-production-westeurope-01 --name debeir-app-production-westeurope-01 --src-path ./minapi.zip

